import { StyleSheet } from 'react-native';
import { colors } from '@/theme';
import { getHeaderTopPadding } from '@/utils/safeArea';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: getHeaderTopPadding(),
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  headerBackButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  // 지도 영역
  mapArea: {
    flex: 1,
    backgroundColor: '#E8F5E9',
    position: 'relative',
  },
  mapPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    overflow: 'hidden',
  },
  mapGridLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  mapGridLine: {
    position: 'absolute',
    backgroundColor: 'rgba(30, 98, 59, 0.12)',
  },
  mapGridHorizontal: {
    left: -24,
    right: -24,
    height: 1,
  },
  mapGridHorizontalTop: {
    top: '28%',
  },
  mapGridHorizontalBottom: {
    top: '58%',
  },
  mapGridVertical: {
    top: -24,
    bottom: -24,
    width: 1,
  },
  mapGridVerticalLeft: {
    left: '24%',
  },
  mapGridVerticalRight: {
    left: '68%',
  },
  mapRoad: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(30, 98, 59, 0.1)',
  },
  mapRoadPrimary: {
    width: '118%',
    height: 34,
    left: '-10%',
    top: '42%',
    transform: [{ rotate: '-12deg' }],
  },
  mapRoadSecondary: {
    width: 30,
    height: '112%',
    left: '36%',
    top: '-8%',
    transform: [{ rotate: '18deg' }],
  },
  mapRoadNeighborhood: {
    width: '76%',
    height: 24,
    right: '-12%',
    top: '22%',
    backgroundColor: '#F6FAF2',
    transform: [{ rotate: '24deg' }],
  },
  mapWaterway: {
    position: 'absolute',
    width: '46%',
    height: 18,
    left: '-8%',
    bottom: '28%',
    borderRadius: 999,
    backgroundColor: '#DCEEFF',
    transform: [{ rotate: '-18deg' }],
  },
  mapEmoji: {
    opacity: 0.2,
    position: 'absolute',
    top: '20%',
    right: '14%',
  },
  radiusCircle: {
    width: 214,
    height: 214,
    borderRadius: 107,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: 'rgba(30, 98, 59, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.primary,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  radiusLabel: {
    position: 'absolute',
    top: '34%',
    right: '13%',
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  radiusText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  gpsStatusChip: {
    position: 'absolute',
    top: 20,
    left: 20,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.24)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  gpsStatusText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  coordinateChip: {
    position: 'absolute',
    left: 20,
    bottom: 142,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(30, 98, 59, 0.1)',
    gap: 2,
  },
  coordinateLabel: {
    color: colors.textTertiary,
    fontSize: 11,
    fontWeight: '600',
  },
  coordinateValue: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  fridgeMapMarker: {
    position: 'absolute',
    right: 28,
    bottom: 170,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(30, 98, 59, 0.14)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  fridgeMarkerIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight,
  },
  fridgeMarkerLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  // 위치 카드
  locationCard: {
    position: 'absolute',
    bottom: 32,
    left: 24,
    right: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  locationPin: {
    fontSize: 16,
  },
  locationName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  locationHint: {
    fontSize: 14,
    color: colors.textTertiary,
    lineHeight: 20,
  },
  locationIssueBox: {
    marginTop: 16,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F8D7DA',
    backgroundColor: '#FFF5F5',
    gap: 8,
  },
  locationIssueTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  locationIssueMessage: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  locationIssueActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  locationIssuePrimaryButton: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationIssuePrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  locationIssueSecondaryButton: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationIssueSecondaryButtonText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  // 하단
  footer: {
    gap: 12,
  },
  notificationPanel: {
    minHeight: 96,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 10,
  },
  notificationTextGroup: {
    flexShrink: 1,
    gap: 4,
  },
  notificationTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  notificationHint: {
    fontSize: 13,
    color: colors.textTertiary,
    lineHeight: 18,
  },
  notificationButton: {
    alignSelf: 'flex-start',
    minWidth: 112,
    minHeight: 40,
    borderRadius: 8,
  },
  notificationButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  submitButton: {
    minHeight: 56,
    borderRadius: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
});
