import { StyleSheet } from 'react-native';
import { colors } from '@/theme';
import { getHeaderTopPadding } from '@/utils/safeArea';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  galleryFallbackButton: {
    backgroundColor: colors.background,
    width: '100%',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 10,
  },
  galleryFallbackButtonText: {
    color: colors.primary,
    fontWeight: 'bold',
  },
  secondaryFallbackButton: {
    width: '100%',
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.44)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  secondaryFallbackText: {
    color: colors.textOnPrimary,
    fontWeight: 'bold',
  },
  fallbackContainer: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingTop: getHeaderTopPadding() + 12,
    paddingBottom: 32,
  },
  fallbackCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  fallbackContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  fallbackPreview: {
    height: 260,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
  },
  fallbackPreviewIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    marginBottom: 16,
  },
  fallbackPreviewCaption: {
    marginTop: 0,
    fontWeight: '700',
  },
  fallbackTitle: {
    marginBottom: 10,
    color: colors.textOnPrimary,
  },
  fallbackDescription: {
    lineHeight: 24,
    marginBottom: 14,
    color: 'rgba(255,255,255,0.82)',
  },
  fallbackActions: {
    marginTop: 4,
    alignItems: 'stretch',
  },
  // 헤더
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: getHeaderTopPadding(),
    zIndex: 10,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    fontSize: 22,
    color: '#FFFFFF',
  },
  statusBadge: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.92)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
  },
  statusSpinner: {
    marginRight: 6,
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  // 카메라 뷰
  cameraContainer: {
    flex: 1,
    position: 'relative',
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
    pointerEvents: 'none',
    backgroundColor: 'transparent',
  },
  scanMask: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.62)',
  },
  scanMaskLeft: {
    left: 0,
    right: undefined,
  },
  scanMaskRight: {
    right: 0,
    left: undefined,
  },
  scanFrame: {
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.01)',
  },
  scanLine: {
    width: '100%',
    height: 3,
    backgroundColor: '#EAFBF0',
    opacity: 0.95,
    shadowColor: '#EAFBF0',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  // 하단 컨트롤
  controls: {
    height: 120,
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingBottom: 20,
    gap: 16,
  },
  captureRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  sideButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sideButtonIcon: {
    fontSize: 20,
  },
  shutterContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shutterDisabled: {
    opacity: 0.5,
  },
  shutterButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
  },
});
