/**
 * Post / AI / Fridge 타입 정의
 */

export type PostStatus =
  | 'pending_store'
  | 'available'
  | 'requested'
  | 'completed'
  | 'expired'
  | 'disposed'
  | 'cancelled';

export type PostCreateFlow = 'direct' | 'fridge_qr';

export type PostStorageZone = 'GENERAL' | 'ETHYLENE_SEPARATED';

export type FreshnessLabel = 'Fresh' | 'Mid' | 'Stale' | 'unknown';

export interface Post {
  id: number;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  confidenceScore?: number | null;
  imageUrl: string;
  expirationDate: string;
  status: PostStatus;
  fridgeId: number;
  authorId: number;
  userId?: number;
  requestExpiresAt?: string | null;
  storeExpiresAt?: string | null;
  pickedUpAt?: string | null;
  labelCode?: string | null;
  storageZone?: PostStorageZone | string | null;
  storageDeadlineAt?: string | null;
  storedAt?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface PostNearbyRead {
  id: number;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  imageUrl: string;
  expirationDate: string;
  status: PostStatus;
  fridgeId: number;
  fridgeName: string;
  requestExpiresAt?: never;
  pickedUpAt?: never;
  labelCode?: never;
  storageZone?: never;
  storageDeadlineAt?: never;
  storedAt?: never;
  createdAt: string;
  confidenceScore?: never;
  authorId?: never;
  userId?: never;
  latitude?: never;
  longitude?: never;
  updatedAt?: never;
}

export interface AiAnalysis {
  isFresh: boolean;
  confidenceScore?: number | null;
  category?: FreshnessLabel | string | null;
  analysisMessage?: string | null;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  detections?: AiDetection[] | null;
  analysisSkipped?: boolean;
  rejectionReason?: string | null;
  reviewReason?: string | null;
}

export interface AiDetection {
  id?: string | number | null;
  label?: string | null;
  labelKo?: string | null;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  confidenceScore?: number | null;
  bbox?: {
    x: number;
    y: number;
    width: number;
    height: number;
  } | null;
}

export interface GenerateResult {
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  confidenceScore?: number | null;
  isFresh?: boolean;
  aiAnalysis: AiAnalysis;
  rejectionReason?: string | null;
  detections?: AiDetection[] | null;
  isAutoGenerated: boolean;
  imageToken?: string | null;
}

export interface PostCreateData {
  fridgeId: number;
  expirationDate: string;
  imageToken: string;
  flow?: PostCreateFlow;
}

export type ShareRequestStatus =
  | 'requested'
  | 'completed'
  | 'cancelled'
  | 'expired';

export interface ShareRequest {
  id: number;
  postId: number;
  requesterId: number;
  status: ShareRequestStatus | string;
  createdAt: string;
}

export interface ShareRequestResult {
  request: ShareRequest;
  post: Post;
}

export interface UserShareRequestItem {
  request: ShareRequest;
  post: Post;
  fridge?: {
    id?: number;
    name?: string;
    address?: string;
    publicCode?: string | null;
  } | null;
}

export type UserPostStatusFilter = PostStatus | 'all';
export type UserShareRequestStatusFilter = ShareRequestStatus | 'all';

export interface Fridge {
  id: number;
  name: string;
  address: string;
  publicCode?: string;
  latitude: number;
  longitude: number;
  isActive: boolean;
  distance?: number;
}
