/**
 * Post / AI / Fridge 타입 정의
 */

export type PostStatus = 'available' | 'requested' | 'completed';

export type FreshnessLabel = 'Fresh' | 'Mid' | 'Stale' | 'unknown';

export interface Post {
  id: number;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  confidenceScore?: number | null;
  imageUrl: string;
  expirationDate: string;
  status: PostStatus;
  fridgeId: number;
  authorId: number;
  userId?: number;
  latitude?: number | null;
  longitude?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface PostNearbyRead {
  id: number;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  imageUrl: string;
  expirationDate: string;
  status: PostStatus;
  fridgeId: number;
  fridgeName: string;
  createdAt: string;
  confidenceScore?: never;
  authorId?: never;
  userId?: never;
  latitude?: never;
  longitude?: never;
  updatedAt?: never;
}

export interface AiAnalysis {
  isFresh: boolean;
  confidenceScore?: number | null;
  category?: FreshnessLabel | string | null;
  analysisMessage?: string | null;
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  analysisSkipped?: boolean;
  rejectionReason?: string | null;
  reviewReason?: string | null;
}

export interface GenerateResult {
  detectedFruit?: string | null;
  detectedFruitKo?: string | null;
  freshnessLabel?: FreshnessLabel | string | null;
  confidenceScore?: number | null;
  isFresh?: boolean;
  aiAnalysis: AiAnalysis;
  isAutoGenerated: boolean;
  imageToken?: string | null;
}

export interface PostCreateData {
  fridgeId: number;
  expirationDate: string;
  imageToken: string;
}

export type ShareRequestStatus = 'requested';

export interface ShareRequest {
  id: number;
  postId: number;
  requesterId: number;
  status: ShareRequestStatus | string;
  createdAt: string;
}

export interface ShareRequestResult {
  request: ShareRequest;
  post: Post;
}

export interface Fridge {
  id: number;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  isActive: boolean;
  distance?: number;
}
