/**
 * Post / Fridge 관련 타입 정의
 */

export interface Post {
  id: number;
  title: string;
  description: string;
  category: string;
  imageUrl: string;
  expirationDate: string;
  fridgeId: number;
  authorId: number;
  userId?: number;
  createdAt: string;
  updatedAt: string;
}

export interface AiAnalysis {
  isFresh: boolean;
  confidenceScore: number;
  category: string;
  analysisMessage: string;
  detectedFruit?: string;
  detectedFruitKo?: string;
  analysisSkipped?: boolean;
  rejectionReason?: string | null;
  reviewReason?: string | null;
}

export interface GenerateResult {
  suggestedTitle: string;
  suggestedDescription: string;
  suggestedCategory: string;
  detectedFruit?: string;
  detectedFruitKo?: string;
  aiAnalysis: AiAnalysis;
  isAutoGenerated: boolean;
  imageToken: string;
}

export interface PostCreateData {
  title: string;
  description: string;
  category: string;
  fridgeId: number;
  expirationDate: string;
  imageToken: string;
}

export interface Fridge {
  id: number;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  isActive: boolean;
  distance?: number;
}
