import { StyleSheet } from 'react-native';
import { colors } from '@/theme';
import { getHeaderTopPadding } from '@/utils/safeArea';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    position: 'absolute',
    top: getHeaderTopPadding(8),
    left: 16,
    right: 16,
    zIndex: 10,
  },
  searchFieldContainer: {
    gap: 0,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 0,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    paddingHorizontal: 0,
  },
  markerWrapper: {
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  markerWrapperSelected: {
    backgroundColor: colors.primary,
    borderColor: '#FFFFFF',
    transform: [{ scale: 1.2 }],
  },
  markerIcon: {
    width: 20,
  },
  mapFallbackLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#EEF5ED',
    overflow: 'hidden',
    zIndex: 1,
  },
  mapDistrictNorth: {
    position: 'absolute',
    top: '20%',
    left: '9%',
    width: '34%',
    height: '18%',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    borderWidth: 1,
    borderColor: 'rgba(98, 142, 78, 0.16)',
  },
  mapDistrictSouth: {
    position: 'absolute',
    right: '7%',
    bottom: '30%',
    width: '38%',
    height: '21%',
    borderRadius: 28,
    backgroundColor: 'rgba(252, 225, 129, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(171, 184, 99, 0.18)',
  },
  mapFallbackRoad: {
    position: 'absolute',
    height: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(30, 98, 59, 0.08)',
  },
  mapFallbackRoadPrimary: {
    top: '45%',
    left: '-8%',
    width: '118%',
    transform: [{ rotate: '-16deg' }],
  },
  mapFallbackRoadSecondary: {
    top: '35%',
    left: '19%',
    width: '82%',
    transform: [{ rotate: '28deg' }],
  },
  mapFallbackRoadTertiary: {
    top: '61%',
    left: '4%',
    width: '72%',
    transform: [{ rotate: '12deg' }],
  },
  mapFallbackGpsRing: {
    position: 'absolute',
    top: '49%',
    left: '47%',
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 2,
    borderColor: 'rgba(30, 98, 59, 0.32)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(232, 245, 233, 0.72)',
  },
  mapFallbackGpsDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary,
  },
  mapFallbackMarker: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: 180,
    paddingVertical: 5,
    paddingHorizontal: 7,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(30, 98, 59, 0.14)',
    gap: 5,
  },
  mapFallbackMarkerIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapFallbackMarkerLabel: {
    color: colors.textPrimary,
    maxWidth: 130,
  },
  myLocationButton: {
    position: 'absolute',
    bottom: 200,
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 12,
  },
  bottomSurface: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    zIndex: 12,
    gap: 12,
  },
  locationRequiredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    backgroundColor: colors.surface,
  },
  locationRequiredTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  locationRequiredText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
  listContent: {
    paddingHorizontal: 16,
    gap: 16,
  },
  card: {
    width: 280,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  cardSelected: {
    backgroundColor: colors.primary,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  cardAddress: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardDistance: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  detailButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderColor: colors.surface,
    minHeight: 30,
  },
  detailButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  textSelected: {
    color: '#FFFFFF',
  },
  emptyCard: {
    marginHorizontal: 24,
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 8,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    minHeight: 38,
  },
  retryButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  selectedFridgeSheet: {
    marginHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  selectedFridgeActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
  },
  switchFridgeButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderColor: colors.surface,
    minHeight: 32,
  },
  switchFridgeButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  selectedFridgeSummary: {
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  selectedFridgeName: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  selectedFridgeAddress: {
    marginTop: 4,
    fontSize: 13,
    color: colors.textSecondary,
  },
  selectedFridgeMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectedFridgeDistance: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  fridgePostsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 10,
    gap: 12,
  },
  fridgePostsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  panelRetryButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: colors.primaryLight,
    borderColor: colors.primaryLight,
    minHeight: 32,
  },
  panelRetryButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  fridgePostsList: {
    maxHeight: 208,
  },
  fridgePostItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 10,
  },
  fridgePostImage: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  fridgePostsStateBox: {
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingTop: 14,
    paddingBottom: 6,
    alignItems: 'center',
  },
  fridgePostsStateTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  fridgePostsStateText: {
    marginTop: 6,
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
  },
});
