import {
  getDetectionName,
  getDetectionSummary,
  getResultDetections,
  hasMultipleDetections,
} from '@/utils/aiDetections';
import type {GenerateResult} from '@/types';

const baseResult: GenerateResult = {
  detectedFruit: 'banana',
  detectedFruitKo: '바나나',
  freshnessLabel: 'Fresh',
  confidenceScore: 0.9,
  isFresh: true,
  aiAnalysis: {
    isFresh: true,
    category: 'Fresh',
  },
  isAutoGenerated: true,
  imageToken: 'image-token',
};

describe('ai detection helpers', () => {
  it('reads detections from the root result before the nested analysis object', () => {
    const result: GenerateResult = {
      ...baseResult,
      detections: [{labelKo: '사과'}],
      aiAnalysis: {
        ...baseResult.aiAnalysis,
        detections: [{labelKo: '토마토'}, {labelKo: '상추'}],
      },
    };

    expect(getResultDetections(result)).toEqual([{labelKo: '사과'}]);
    expect(hasMultipleDetections(result)).toBe(false);
  });

  it('formats candidate names and quality summaries defensively', () => {
    expect(getDetectionName({labelKo: '토마토', label: 'tomato'})).toBe(
      '토마토',
    );
    expect(
      getDetectionSummary({
        freshnessLabel: 'Fresh',
        confidenceScore: 0.94,
      }),
    ).toBe('상태가 좋아 보여요');
    expect(getDetectionSummary({freshnessLabel: 'unknown'})).toBe(
      '사진으로 상태를 확인하기 어려워요',
    );
  });
});
