import React from 'react';
import {Text, TouchableOpacity} from 'react-native';
import ReactTestRenderer from 'react-test-renderer';
import AnalysisResultScreen from '@/screens/camera/AnalysisResultScreen';
import type {GenerateResult} from '@/types';
import {renderWithSafeArea} from '../test-utils/renderWithSafeArea';

const baseResult: GenerateResult = {
  detectedFruit: 'apple',
  detectedFruitKo: '사과',
  freshnessLabel: 'Fresh',
  confidenceScore: 0.95,
  isFresh: true,
  aiAnalysis: {
    isFresh: true,
    category: 'Fresh',
    detectedFruit: 'apple',
    detectedFruitKo: '사과',
    confidenceScore: 0.95,
    analysisMessage: '상태가 좋아 보여요. 나눔이 가능합니다.',
  },
  isAutoGenerated: true,
  imageToken: 'image-token-1',
};

const createScreen = async (result: GenerateResult) => {
  let renderer: ReactTestRenderer.ReactTestRenderer | undefined;
  const navigation = {
    goBack: jest.fn(),
    replace: jest.fn(),
  };

  await ReactTestRenderer.act(async () => {
    renderer = ReactTestRenderer.create(
      renderWithSafeArea(
        <AnalysisResultScreen
          navigation={navigation as never}
          route={{params: {result, imageUri: 'file:///scan.jpg'}} as never}
        />,
      ),
    );
  });

  if (!renderer) {
    throw new Error('renderer was not created');
  }

  return {renderer, navigation};
};

const findButtonByText = (
  renderer: ReactTestRenderer.ReactTestRenderer,
  label: string,
) =>
  renderer.root.findAllByType(TouchableOpacity).find(button =>
    button.findAllByType(Text).some(textNode => {
      const children = textNode.props.children;
      return Array.isArray(children)
        ? children.join('') === label
        : children === label;
    }),
  );

describe('AnalysisResultScreen fallback QA', () => {
  it('blocks share registration when AI says the image does not meet share criteria', async () => {
    const {renderer, navigation} = await createScreen({
      ...baseResult,
      freshnessLabel: 'Stale',
      confidenceScore: 0.88,
      isFresh: false,
      aiAnalysis: {
        ...baseResult.aiAnalysis,
        isFresh: false,
        category: 'Stale',
        confidenceScore: 0.88,
        analysisMessage: '나눔 기준에 맞지 않아요.',
      },
      imageToken: null,
    });

    const blockedButton = findButtonByText(renderer, '나눔 기준 미충족');

    expect(blockedButton?.props.disabled).toBe(true);
    expect(navigation.replace).not.toHaveBeenCalled();

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('blocks share registration when generate did not return an imageToken', async () => {
    const {renderer} = await createScreen({
      ...baseResult,
      imageToken: null,
    });

    const blockedButton = findButtonByText(renderer, '나눔 기준 미충족');

    expect(blockedButton?.props.disabled).toBe(true);

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('marks low confidence as review but still allows share registration when imageToken exists', async () => {
    const lowConfidenceResult = {
      ...baseResult,
      confidenceScore: 0.7,
      aiAnalysis: {
        ...baseResult.aiAnalysis,
        confidenceScore: 0.7,
      },
    };
    const {renderer, navigation} = await createScreen(lowConfidenceResult);

    expect(
      renderer.root.findAllByProps({children: '확인 필요'}),
    ).not.toHaveLength(0);
    expect(
      renderer.root.findAllByProps({children: 'AI 참고 신호'}),
    ).toHaveLength(0);
    expect(
      renderer.root.findAllByProps({
        children:
          'AI가 나눔 가능으로 분석했지만 실제 상태를 직접 확인한 뒤 등록해주세요.',
      }),
    ).not.toHaveLength(0);

    const nextButton = findButtonByText(renderer, '이대로 나눔하기');
    expect(nextButton?.props.disabled).toBe(false);

    await ReactTestRenderer.act(async () => {
      nextButton?.props.onPress();
    });

    expect(navigation.replace).toHaveBeenCalledWith('PostCreate', {
      result: lowConfidenceResult,
      imageUri: 'file:///scan.jpg',
    });

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('shows shareable and excluded detections when the backend sends multi-object detections', async () => {
    const multiObjectResult: GenerateResult = {
      ...baseResult,
      detections: [
        {
          label: 'banana',
          labelKo: '바나나',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.96,
          shareable: true,
        },
        {
          label: 'tomato',
          labelKo: '토마토',
          freshnessLabel: 'Stale',
          confidenceScore: 0.82,
          shareable: false,
        },
      ],
    };

    const {renderer} = await createScreen(multiObjectResult);

    expect(
      renderer.root.findAllByProps({children: '감지된 식재료'}),
    ).not.toHaveLength(0);
    expect(renderer.root.findAllByProps({children: '바나나'})).not.toHaveLength(
      0,
    );
    expect(renderer.root.findAllByProps({children: '토마토'})).not.toHaveLength(
      0,
    );
    expect(
      renderer.root.findAllByProps({
        children: '1개 품목이 나눔 등록 대상입니다.',
      }),
    ).not.toHaveLength(0);
    expect(
      renderer.root.findAllByProps({
        children: '보관 기준에 맞지 않아 나눔 목록에서 제외됩니다.',
      }),
    ).not.toHaveLength(0);

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });
});
