import React from 'react';
import {
  Alert,
  Animated,
  Linking,
  StyleSheet,
  Text,
  TouchableOpacity,
} from 'react-native';
import {launchImageLibrary} from 'react-native-image-picker';
import ReactTestRenderer from 'react-test-renderer';
import CameraScanScreen from '@/screens/camera/CameraScanScreen';
import {generatePost} from '@/api/posts';

jest.mock('@/api/posts', () => ({
  generatePost: jest.fn(),
}));

let mockHasCameraPermission = true;
let mockCameraDevice: unknown = null;
const mockRequestCameraPermission = jest.fn();

jest.mock('react-native-vision-camera', () => {
  const ReactForMock = require('react');
  const {View: MockView} = require('react-native');

  return {
    Camera: ReactForMock.forwardRef((props: unknown, ref: React.Ref<unknown>) =>
      ReactForMock.createElement(MockView, {...(props as object), ref}),
    ),
    useCameraDevice: jest.fn(() => mockCameraDevice),
    useCameraPermission: jest.fn(() => ({
      hasPermission: mockHasCameraPermission,
      requestPermission: mockRequestCameraPermission,
    })),
    usePhotoOutput: jest.fn(() => ({
      capturePhotoToFile: jest.fn(),
    })),
  };
});

const mockedLaunchImageLibrary = launchImageLibrary as jest.MockedFunction<
  typeof launchImageLibrary
>;
const mockedGeneratePost = generatePost as jest.MockedFunction<
  typeof generatePost
>;

const createScreen = async () => {
  let renderer: ReactTestRenderer.ReactTestRenderer | undefined;
  const navigation = {
    goBack: jest.fn(),
    replace: jest.fn(),
  };

  await ReactTestRenderer.act(async () => {
    renderer = ReactTestRenderer.create(
      <CameraScanScreen navigation={navigation as never} route={{} as never} />,
    );
    await Promise.resolve();
  });

  if (!renderer) {
    throw new Error('renderer was not created');
  }

  return {renderer, navigation};
};

const findButtonByText = (
  renderer: ReactTestRenderer.ReactTestRenderer,
  label: string,
) =>
  renderer.root.findAllByType(TouchableOpacity).find(button =>
    button.findAllByType(Text).some(textNode => {
      const children = textNode.props.children;
      return Array.isArray(children)
        ? children.join('') === label
        : children === label;
    }),
  );

describe('CameraScanScreen fallback QA', () => {
  const alertSpy = jest.spyOn(Alert, 'alert').mockImplementation(jest.fn());
  const openSettingsSpy = jest
    .spyOn(Linking, 'openSettings')
    .mockImplementation(jest.fn());
  const warnSpy = jest.spyOn(console, 'warn').mockImplementation(jest.fn());

  beforeEach(() => {
    jest.clearAllMocks();
    mockHasCameraPermission = true;
    mockCameraDevice = null;
    mockRequestCameraPermission.mockResolvedValue(false);
    alertSpy.mockClear();
  });

  afterAll(() => {
    alertSpy.mockRestore();
    openSettingsSpy.mockRestore();
    warnSpy.mockRestore();
  });

  it('offers permission recovery actions when camera permission is missing', async () => {
    mockHasCameraPermission = false;

    const {renderer} = await createScreen();

    expect(
      renderer.root.findAllByProps({testID: 'camera-fallback-surface'}),
    ).not.toHaveLength(0);
    expect(
      renderer.root.findAllByProps({testID: 'camera-fallback-preview'}),
    ).not.toHaveLength(0);
    expect(findButtonByText(renderer, '권한 다시 요청')).toBeTruthy();
    expect(findButtonByText(renderer, '설정 열기')).toBeTruthy();
    expect(findButtonByText(renderer, '갤러리에서 선택하기')).toBeTruthy();

    mockRequestCameraPermission.mockClear();

    await ReactTestRenderer.act(async () => {
      findButtonByText(renderer, '권한 다시 요청')?.props.onPress();
      await Promise.resolve();
    });

    expect(mockRequestCameraPermission).toHaveBeenCalledTimes(1);

    await ReactTestRenderer.act(async () => {
      findButtonByText(renderer, '설정 열기')?.props.onPress();
      await Promise.resolve();
    });

    expect(openSettingsSpy).toHaveBeenCalledTimes(1);

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('uses the gallery fallback when no camera device is available and opens analysis result', async () => {
    mockedLaunchImageLibrary.mockResolvedValue({
      assets: [
        {
          uri: 'file:///gallery/apple.jpg',
          type: 'image/jpeg',
          fileName: 'apple.jpg',
          fileSize: 320000,
        },
      ],
    });
    mockedGeneratePost.mockResolvedValue({
      success: true,
      message: 'AI 분석이 완료되었습니다.',
      data: {
        detectedFruitKo: '사과',
        aiAnalysis: {
          isFresh: true,
          category: 'Fresh',
          detectedFruitKo: '사과',
          confidenceScore: 0.95,
          analysisMessage: '상태가 좋아 보여요. 나눔이 가능합니다.',
        },
        isAutoGenerated: true,
        imageToken: 'image-token-1',
      },
    });

    const {renderer, navigation} = await createScreen();
    const galleryButton = findButtonByText(renderer, '갤러리에서 선택하기');

    expect(
      renderer.root.findAllByProps({testID: 'camera-fallback-surface'}),
    ).not.toHaveLength(0);
    expect(
      renderer.root.findAllByProps({testID: 'camera-fallback-preview'}),
    ).not.toHaveLength(0);
    expect(galleryButton).toBeTruthy();

    await ReactTestRenderer.act(async () => {
      galleryButton?.props.onPress();
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(mockedGeneratePost).toHaveBeenCalledWith({
      uri: 'file:///gallery/apple.jpg',
      type: 'image/jpeg',
      name: 'apple.jpg',
    });
    expect(navigation.replace).toHaveBeenCalledWith('AnalysisResult', {
      result: expect.objectContaining({imageToken: 'image-token-1'}),
      imageUri: 'file:///gallery/apple.jpg',
    });

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('aligns the scan mask cutout with the responsive scan frame', async () => {
    mockCameraDevice = {id: 'back'};
    const loopSpy = jest.spyOn(Animated, 'loop').mockReturnValue({
      start: jest.fn(),
      stop: jest.fn(),
      reset: jest.fn(),
    } as unknown as Animated.CompositeAnimation);

    const {renderer} = await createScreen();

    try {
      const frameStyle = StyleSheet.flatten(
        renderer.root.findByProps({testID: 'camera-scan-frame'}).props.style,
      );
      const bottomMaskStyle = StyleSheet.flatten(
        renderer.root.findByProps({testID: 'camera-scan-bottom-mask'}).props
          .style,
      );

      expect(frameStyle.position).toBe('absolute');
      expect(typeof frameStyle.top).toBe('number');
      expect(typeof frameStyle.left).toBe('number');
      expect(bottomMaskStyle.top).toBe(frameStyle.top + frameStyle.height);
    } finally {
      await ReactTestRenderer.act(async () => {
        renderer.unmount();
      });
      loopSpy.mockRestore();
    }
  });

  it('keeps the user on scan when generate rejects and offers retake or gallery fallback', async () => {
    mockedLaunchImageLibrary.mockResolvedValue({
      assets: [
        {
          uri: 'file:///gallery/stale.jpg',
          type: 'image/jpeg',
          fileName: 'stale.jpg',
          fileSize: 310000,
        },
      ],
    });
    mockedGeneratePost.mockRejectedValue({
      response: {
        status: 400,
        data: {
          message: 'legacy generate error',
          detail: '식재료가 부패한 상태입니다. 게시할 수 없습니다.',
        },
      },
    });

    const {renderer, navigation} = await createScreen();
    const galleryButton = findButtonByText(renderer, '갤러리에서 선택하기');

    await ReactTestRenderer.act(async () => {
      galleryButton?.props.onPress();
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(navigation.replace).not.toHaveBeenCalled();
    expect(alertSpy).toHaveBeenCalledWith(
      '분석 실패',
      '나눔 기준에 맞지 않아요. 다시 촬영해주세요.',
      [
        {text: '다시 촬영', style: 'cancel'},
        {text: '갤러리 선택', onPress: expect.any(Function)},
      ],
    );

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('shows backend AI rejection reason copy when generate returns generic message', async () => {
    mockedLaunchImageLibrary.mockResolvedValue({
      assets: [
        {
          uri: 'file:///gallery/not-food.jpg',
          type: 'image/jpeg',
          fileName: 'not-food.jpg',
          fileSize: 310000,
        },
      ],
    });
    mockedGeneratePost.mockRejectedValue({
      message: 'Request failed with status code 400',
      response: {
        status: 400,
        data: {
          success: false,
          message: 'AI 분석에 실패했습니다.',
          error: {
            code: 'AI_REJECTED',
            rejectionReason: 'not_food',
          },
        },
      },
    });

    const {renderer, navigation} = await createScreen();
    const galleryButton = findButtonByText(renderer, '갤러리에서 선택하기');

    await ReactTestRenderer.act(async () => {
      galleryButton?.props.onPress();
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(navigation.replace).not.toHaveBeenCalled();
    expect(alertSpy).toHaveBeenCalledWith(
      '분석 실패',
      '식재료 사진으로 확인되지 않았어요. 다시 촬영해주세요.',
      [
        {text: '다시 촬영', style: 'cancel'},
        {text: '갤러리 선택', onPress: expect.any(Function)},
      ],
    );

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });

  it('blocks unsupported gallery files before calling generate', async () => {
    mockedLaunchImageLibrary.mockResolvedValue({
      assets: [
        {
          uri: 'file:///gallery/scan.gif',
          type: 'image/gif',
          fileName: 'scan.gif',
          fileSize: 120000,
        },
      ],
    });

    const {renderer} = await createScreen();
    const galleryButton = findButtonByText(renderer, '갤러리에서 선택하기');

    await ReactTestRenderer.act(async () => {
      galleryButton?.props.onPress();
      await Promise.resolve();
    });

    expect(mockedGeneratePost).not.toHaveBeenCalled();
    expect(alertSpy).toHaveBeenCalledWith(
      '업로드 불가',
      '지원하지 않는 이미지 형식입니다. JPG 또는 PNG 사진을 선택해주세요.',
    );

    await ReactTestRenderer.act(async () => {
      renderer.unmount();
    });
  });
});
