import React from 'react';
import ReactTestRenderer from 'react-test-renderer';
import PostCreateScreen from '@/screens/post/PostCreateScreen';
import type {GenerateResult} from '@/types';

const lowConfidenceResult: GenerateResult = {
  detectedFruit: 'banana',
  detectedFruitKo: '바나나',
  freshnessLabel: 'Fresh',
  confidenceScore: 0.79,
  isFresh: true,
  aiAnalysis: {
    isFresh: true,
    category: 'Fresh',
    detectedFruit: 'banana',
    detectedFruitKo: '바나나',
    confidenceScore: 0.79,
    analysisMessage: '상태가 좋아 보여요. 나눔이 가능합니다.',
  },
  isAutoGenerated: true,
  imageToken: 'image-token',
};

describe('PostCreateScreen review notice', () => {
  it('keeps low confidence shareable but asks the user to verify the real item state', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        <PostCreateScreen
          navigation={navigation as never}
          route={{
            params: {
              result: lowConfidenceResult,
              imageUri: 'file:///banana.jpg',
            },
          } as never}
        />,
      );
    });

    expect(
      renderer!.root.findAllByProps({children: 'AI 참고 신호'}),
    ).not.toHaveLength(0);
    expect(
      renderer!.root.findAllByProps({
        children:
          'AI가 나눔 가능으로 분석했지만 실제 상태를 직접 확인한 뒤 등록해주세요.',
      }),
    ).not.toHaveLength(0);
    expect(
      renderer!.root.findAllByProps({children: '다음 단계로'}),
    ).not.toHaveLength(0);

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });
});
