import apiClient from '@/api/client';
import {
  createPost,
  generatePost,
  getImageUrl,
  requestShare,
} from '@/api/posts';
import { API_BASE_URL } from '@/config/api';
import { getToken } from '@/utils/storage';

jest.mock('@/api/client', () => {
  const { API_BASE_URL: actualBaseUrl } = jest.requireActual('@/config/api');
  return {
    __esModule: true,
    default: {
      post: jest.fn(),
    },
    BASE_URL: actualBaseUrl,
  };
});

jest.mock('@/utils/storage', () => ({
  getToken: jest.fn(),
}));

const mockedGetToken = getToken as jest.MockedFunction<typeof getToken>;
const mockedApiClient = apiClient as jest.Mocked<typeof apiClient>;
const testGlobal = globalThis as typeof globalThis & {
  fetch: jest.Mock;
  FormData: typeof FormData;
  XMLHttpRequest: typeof XMLHttpRequest;
};

type MockFetchResponse = {
  ok: boolean;
  status: number;
  json: () => Promise<unknown>;
};

class MockFormData {
  fields: Array<[string, unknown]> = [];

  append(name: string, value: unknown) {
    this.fields.push([name, value]);
  }
}

class MockXMLHttpRequest {
  static instances: MockXMLHttpRequest[] = [];
  static nextResponse = {
    status: 200,
    body: {
      success: true,
      message: 'ok',
      data: {
        detectedFruit: 'apple',
        detectedFruitKo: '사과',
        freshnessLabel: 'Fresh',
        confidenceScore: 1,
        isFresh: true,
        aiAnalysis: {
          isFresh: true,
          confidenceScore: 1,
          category: 'Fresh',
          analysisMessage: '식재료가 신선합니다.',
          detectedFruit: 'apple',
          detectedFruitKo: '사과',
          analysisSkipped: false,
        },
        isAutoGenerated: false,
        imageToken: 'image-token-1',
        rejectionReason: null,
        detections: [
          {
            id: 'detection-1',
            label: 'apple',
            labelKo: '사과',
            freshnessLabel: 'Fresh',
            confidenceScore: 1,
            bbox: null,
          },
        ],
      },
    },
  };

  method = '';
  url = '';
  timeout = 0;
  headers: Record<string, string> = {};
  status = 0;
  responseText = '';
  body: unknown;
  onload: (() => void) | null = null;
  onerror: (() => void) | null = null;
  ontimeout: (() => void) | null = null;

  constructor() {
    MockXMLHttpRequest.instances.push(this);
  }

  open(method: string, url: string) {
    this.method = method;
    this.url = url;
  }

  setRequestHeader(name: string, value: string) {
    this.headers[name] = value;
  }

  send(body: unknown) {
    this.body = body;
    const { status, body: responseBody } = MockXMLHttpRequest.nextResponse;
    this.status = status;
    this.responseText = JSON.stringify(responseBody);
    this.onload?.();
  }
}

describe('posts API contract', () => {
  const originalFetch = testGlobal.fetch;
  const originalFormData = testGlobal.FormData;
  const originalXMLHttpRequest = testGlobal.XMLHttpRequest;

  beforeEach(() => {
    jest.clearAllMocks();
    mockedGetToken.mockResolvedValue('access-token');
    testGlobal.fetch = jest.fn();
    testGlobal.FormData = MockFormData as unknown as typeof FormData;
    testGlobal.XMLHttpRequest =
      MockXMLHttpRequest as unknown as typeof XMLHttpRequest;
    MockXMLHttpRequest.instances = [];
    MockXMLHttpRequest.nextResponse.status = 200;
    mockedApiClient.post.mockReset();
  });

  afterAll(() => {
    testGlobal.fetch = originalFetch;
    testGlobal.FormData = originalFormData;
    testGlobal.XMLHttpRequest = originalXMLHttpRequest;
  });

  it('sends selected image to generate endpoint as multipart form data', async () => {
    const response = await generatePost(
      { uri: 'file:///photo.jpg', type: 'image/jpeg', name: 'photo.jpg' },
      '어제 샀어요',
    );

    const request = MockXMLHttpRequest.instances[0];
    const formData = request.body as MockFormData;

    expect(request.method).toBe('POST');
    expect(request.url).toBe(`${API_BASE_URL}/api/v1/posts/generate`);
    expect(request.timeout).toBe(30000);
    expect(request.headers.Authorization).toBe('Bearer access-token');
    expect(formData.fields).toEqual([
      [
        'image',
        { uri: 'file:///photo.jpg', type: 'image/jpeg', name: 'photo.jpg' },
      ],
      ['user_hint', '어제 샀어요'],
    ]);
    expect(response.data?.imageToken).toBe('image-token-1');
    expect(response.data?.rejectionReason).toBeNull();
    expect(response.data?.detections?.[0]?.id).toBe('detection-1');
    expect(response.data?.detections?.[0]?.bbox).toBeNull();
  });

  it('creates post with encoded JSON data and imageToken only', async () => {
    const postData = {
      fridgeId: 1,
      expirationDate: '2026-05-08',
      imageToken: 'image-token-1',
    };

    testGlobal.fetch.mockResolvedValue({
      ok: true,
      status: 201,
      json: async () => ({
        success: true,
        message: 'created',
        data: {
          id: 10,
          fridgeId: 1,
          authorId: 1,
          detectedFruit: 'apple',
          detectedFruitKo: '사과',
          freshnessLabel: 'Fresh',
          confidenceScore: 1,
          imageUrl: '/static/posts/10.jpg',
          expirationDate: '2026-05-08',
          status: 'available',
          createdAt: '2026-05-06T00:00:00Z',
          updatedAt: '2026-05-06T00:00:00Z',
        },
      }),
    } satisfies MockFetchResponse);

    const response = await createPost(postData);
    const [url, init] = testGlobal.fetch.mock.calls[0];
    const body = init.body as string;

    expect(url).toBe(`${API_BASE_URL}/api/v1/posts`);
    expect(init.method).toBe('POST');
    expect(init.headers).toEqual({
      Authorization: 'Bearer access-token',
      'Content-Type': 'application/x-www-form-urlencoded',
    });
    expect(body.startsWith('data=')).toBe(true);
    expect(JSON.parse(decodeURIComponent(body.slice('data='.length)))).toEqual(
      postData,
    );
    expect(body).toContain(encodeURIComponent('image-token-1'));
    expect(body).not.toContain('file:///photo.jpg');
    expect(response.data?.id).toBe(10);
  });

  it('passes fridge QR flow through post creation without changing the endpoint', async () => {
    const postData = {
      fridgeId: 1,
      expirationDate: '2026-05-08',
      imageToken: 'image-token-1',
      flow: 'fridge_qr' as const,
    };

    testGlobal.fetch.mockResolvedValue({
      ok: true,
      status: 201,
      json: async () => ({
        success: true,
        message: 'pending store created',
        data: {
          id: 11,
          fridgeId: 1,
          authorId: 1,
          imageUrl: '/static/posts/11.jpg',
          expirationDate: '2026-05-08',
          status: 'pending_store',
          createdAt: '2026-05-06T00:00:00Z',
          updatedAt: '2026-05-06T00:00:00Z',
        },
      }),
    } satisfies MockFetchResponse);

    const response = await createPost(postData);
    const [, init] = testGlobal.fetch.mock.calls[0];
    const body = init.body as string;

    expect(JSON.parse(decodeURIComponent(body.slice('data='.length)))).toEqual(
      postData,
    );
    expect(response.data?.status).toBe('pending_store');
  });

  it('preserves server error status and message when post creation fails', async () => {
    const errorBody = {
      success: false,
      message: '이미지가 만료되었거나 유효하지 않습니다. 다시 촬영해주세요.',
      data: null,
    };

    testGlobal.fetch.mockResolvedValue({
      ok: false,
      status: 400,
      json: async () => errorBody,
    } satisfies MockFetchResponse);

    await expect(
      createPost({
        fridgeId: 1,
        expirationDate: '2026-05-08',
        imageToken: 'expired-token',
      }),
    ).rejects.toMatchObject({
      response: { status: 400, data: errorBody },
    });
  });

  it('requests a share for a specific post and returns request plus updated post', async () => {
    mockedApiClient.post.mockResolvedValue({
      data: {
        success: true,
        message: '나눔 신청이 완료되었습니다.',
        data: {
          request: {
            id: 1,
            postId: 10,
            requesterId: 2,
            status: 'requested',
            createdAt: '2026-05-06T00:00:00Z',
          },
          post: {
            id: 10,
            fridgeId: 1,
            authorId: 1,
            detectedFruit: 'apple',
            detectedFruitKo: '사과',
            freshnessLabel: 'Fresh',
            confidenceScore: 1,
            imageUrl: '/static/posts/10.jpg',
            expirationDate: '2026-05-08',
            status: 'requested',
            requestExpiresAt: '2026-05-19T14:00:00Z',
            createdAt: '2026-05-06T00:00:00Z',
            updatedAt: '2026-05-06T00:00:00Z',
          },
        },
      },
    });

    const response = await requestShare(10);

    expect(mockedApiClient.post).toHaveBeenCalledWith(
      '/api/v1/posts/10/requests',
    );
    expect(response.data?.request.id).toBe(1);
    expect(response.data?.post.status).toBe('requested');
    expect(response.data?.post.requestExpiresAt).toBe(
      '2026-05-19T14:00:00Z',
    );
  });

  it('builds absolute image URLs from server relative paths', () => {
    expect(getImageUrl('/static/uploads/posts/1/apple.jpg')).toBe(
      `${API_BASE_URL}/static/uploads/posts/1/apple.jpg`,
    );
  });
});
