import React from 'react';
import {Alert, Text, TextInput, TouchableOpacity} from 'react-native';
import ReactTestRenderer from 'react-test-renderer';
import PostCreateScreen from '@/screens/post/PostCreateScreen';
import type {GenerateResult} from '@/types';
import {renderWithSafeArea} from '../test-utils/renderWithSafeArea';

const lowConfidenceResult: GenerateResult = {
  detectedFruit: 'banana',
  detectedFruitKo: '바나나',
  freshnessLabel: 'Fresh',
  confidenceScore: 0.79,
  isFresh: true,
  aiAnalysis: {
    isFresh: true,
    category: 'Fresh',
    detectedFruit: 'banana',
    detectedFruitKo: '바나나',
    confidenceScore: 0.79,
    analysisMessage: '상태가 좋아 보여요. 나눔이 가능합니다.',
  },
  isAutoGenerated: true,
  imageToken: 'image-token',
};

const childrenMatchText = (children: unknown, text: string) =>
  Array.isArray(children) ? children.join('') === text : children === text;

const findTouchableByText = (
  renderer: ReactTestRenderer.ReactTestRenderer,
  label: string,
) => {
  const button = renderer.root.findAllByType(TouchableOpacity).find(touchable =>
    touchable
      .findAllByType(Text)
      .some(textNode => childrenMatchText(textNode.props.children, label)),
  );

  if (!button) {
    throw new Error(`Touchable not found: ${label}`);
  }

  return button;
};

const pressFooterSubmit = async (
  renderer: ReactTestRenderer.ReactTestRenderer,
) => {
  await ReactTestRenderer.act(async () => {
    findTouchableByText(renderer, '다음 단계로').props.onPress();
  });
};

const pressCandidate = async (
  renderer: ReactTestRenderer.ReactTestRenderer,
  label: string,
) => {
  await ReactTestRenderer.act(async () => {
    findTouchableByText(renderer, label).props.onPress();
  });
};

const hasText = (renderer: ReactTestRenderer.ReactTestRenderer, text: string) =>
  renderer.root.findAllByType(Text).some(textNode => {
    const children = textNode.props.children;

    return Array.isArray(children)
      ? children.join('').includes(text)
      : typeof children === 'string' && children.includes(text);
  });

describe('PostCreateScreen review notice', () => {
  const alertSpy = jest.spyOn(Alert, 'alert').mockImplementation(jest.fn());

  beforeEach(() => {
    jest.clearAllMocks();
    jest.useFakeTimers();
    jest.setSystemTime(new Date('2026-05-18T12:00:00Z'));
  });

  afterEach(() => {
    jest.useRealTimers();
    alertSpy.mockClear();
  });

  afterAll(() => {
    alertSpy.mockRestore();
  });

  it('keeps low confidence shareable but asks the user to verify the real item state', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: lowConfidenceResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    expect(hasText(renderer!, '79%')).toBe(false);
    expect(hasText(renderer!, 'AI 참고 신호')).toBe(false);
    expect(hasText(renderer!, '바나나')).toBe(true);

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('lets the user adjust the recommended pickup date within the short MVP window', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: lowConfidenceResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    expect(hasText(renderer!, '2026-05-21')).toBe(true);
    expect(hasText(renderer!, '최대 3일')).toBe(true);

    await pressCandidate(renderer!, '내일');

    await pressFooterSubmit(renderer!);

    expect(navigation.navigate).toHaveBeenCalledWith('FridgeSelect', {
      postData: {
        imageToken: 'image-token',
        expirationDate: '2026-05-19',
      },
      qualityCategory: 'Fresh',
      qualityCanShare: true,
    });

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('does not expose free-form pickup date input or arbitrary long deadlines', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: lowConfidenceResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    expect(renderer!.root.findAllByType(TextInput)).toHaveLength(0);
    expect(hasText(renderer!, 'YYYY-MM-DD')).toBe(false);
    expect(hasText(renderer!, '오늘')).toBe(true);
    expect(hasText(renderer!, '내일')).toBe(true);
    expect(hasText(renderer!, '3일 뒤')).toBe(true);
    expect(hasText(renderer!, '오늘부터 3일 안에서만')).toBe(true);
    expect(hasText(renderer!, '30일')).toBe(false);

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('selects a multi-object representative and forwards its detection id', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };
    const multiObjectResult: GenerateResult = {
      ...lowConfidenceResult,
      detections: [
        {
          id: 'banana-detection',
          label: 'banana',
          labelKo: '바나나',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.92,
        },
        {
          id: 'apple-detection',
          label: 'apple',
          labelKo: '사과',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.89,
        },
      ],
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: multiObjectResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    expect(
      renderer!.root.findAllByProps({children: '바나나'}),
    ).not.toHaveLength(0);
    expect(
      renderer!.root.findAllByProps({children: '사과'}),
    ).not.toHaveLength(0);

    await pressCandidate(renderer!, '사과');
    await pressFooterSubmit(renderer!);

    expect(navigation.navigate).toHaveBeenCalledWith('FridgeSelect', {
      postData: {
        imageToken: 'image-token',
        expirationDate: '2026-05-21',
        selectedDetectionId: 'apple-detection',
      },
      qualityCategory: 'Fresh',
      qualityCanShare: true,
    });

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('explains representative selection and QR store verification without backend contract wording', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };
    const multiObjectResult: GenerateResult = {
      ...lowConfidenceResult,
      detections: [
        {
          id: 'banana-detection',
          label: 'banana',
          labelKo: '바나나',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.92,
        },
        {
          id: 'apple-detection',
          label: 'apple',
          labelKo: '사과',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.89,
        },
      ],
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: multiObjectResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    expect(hasText(renderer!, '백엔드 분리 등록 계약')).toBe(false);
    expect(hasText(renderer!, '대표 식재료 1개를 선택해 등록합니다.')).toBe(
      true,
    );
    expect(hasText(renderer!, '나눔 가능 상태로 등록')).toBe(false);
    expect(hasText(renderer!, '등록될 나눔 식재료')).toBe(false);
    expect(hasText(renderer!, '나눔 식재료')).toBe(true);
    expect(hasText(renderer!, 'QR 보관 인증 대기 상태로 생성됩니다.')).toBe(
      true,
    );

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('resets the selected representative when a new analysis result arrives', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };
    const initialResult: GenerateResult = {
      ...lowConfidenceResult,
      detections: [
        {
          id: 'initial-banana-detection',
          label: 'initial-banana',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.92,
        },
        {
          id: 'initial-apple-detection',
          label: 'initial-apple',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.89,
        },
      ],
    };
    const nextResult: GenerateResult = {
      ...lowConfidenceResult,
      imageToken: 'next-image-token',
      detections: [
        {
          id: 'next-carrot-detection',
          label: 'next-carrot',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.91,
        },
        {
          id: 'next-pepper-detection',
          label: 'next-pepper',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.88,
        },
      ],
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: initialResult,
                  imageUri: 'file:///initial.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    await pressCandidate(renderer!, 'initial-apple');

    await ReactTestRenderer.act(async () => {
      renderer!.update(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: nextResult,
                  imageUri: 'file:///next.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    await pressFooterSubmit(renderer!);

    expect(navigation.navigate).toHaveBeenCalledWith('FridgeSelect', {
      postData: {
        imageToken: 'next-image-token',
        expirationDate: '2026-05-21',
        selectedDetectionId: 'next-carrot-detection',
      },
      qualityCategory: 'Fresh',
      qualityCanShare: true,
    });

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });

  it('omits selectedDetectionId when selected multi-object candidate has no id', async () => {
    const navigation = {
      goBack: jest.fn(),
      navigate: jest.fn(),
    };
    const multiObjectResult: GenerateResult = {
      ...lowConfidenceResult,
      detections: [
        {
          label: 'banana',
          labelKo: '바나나',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.92,
        },
        {
          label: 'apple',
          labelKo: '사과',
          freshnessLabel: 'Fresh',
          confidenceScore: 0.89,
        },
      ],
    };

    let renderer: ReactTestRenderer.ReactTestRenderer | undefined;

    await ReactTestRenderer.act(async () => {
      renderer = ReactTestRenderer.create(
        renderWithSafeArea(
          <PostCreateScreen
            navigation={navigation as never}
            route={
              {
                params: {
                  result: multiObjectResult,
                  imageUri: 'file:///banana.jpg',
                },
              } as never
            }
          />,
        ),
      );
    });

    await pressFooterSubmit(renderer!);

    expect(navigation.navigate).toHaveBeenCalledWith('FridgeSelect', {
      postData: {
        imageToken: 'image-token',
        expirationDate: '2026-05-21',
      },
      qualityCategory: 'Fresh',
      qualityCanShare: true,
    });

    await ReactTestRenderer.act(async () => {
      renderer!.unmount();
    });
  });
});
